### PR TITLE
Issue 33 add scheduled scaling

### PR DESCRIPTION
**Pull request by parabolic**
Solves https://github.com/blinkist/terraform-aws-airship-ecs-service/issues/33

Add a sub module `ecs_scheduled_tasks` to be used for scheduled task scaling using cron, at or rate expressions. 
https://docs.aws.amazon.com/autoscaling/application/userguide/application-auto-scaling-scheduled-scaling.html

The following parameters need to be passed in order to activate this sub module
```hcl
  schedule_scale_down    = "cron(15 10 ? * 6L 2002-2005)"
  schedule_scale_up      = "cron(15 10 ? * 6L 2002-2005)"
```
It works in conjunction with the  existing sub module `ecs_autoscaling` by utlizing the `aws_appautoscaling_target` resource from it and using its attributes only if the `ecs_autoscaling` module is created.

### CODE REVIEW

**Comment by mhvelplund** [comment]
Hi @parabolic . If you fixed the requested changes and resolved the merge conflicts, maybe I could take a look at th review and merge for you?

**Comment by parabolic** [comment]
HI @mhvelplund thanks, I don't see any requested changes, only conflicts. I will resolve them.

Cheers!

**Comment by mhvelplund** [comment]
This is not happening, apparently.

**Comment by parabolic** [comment]
Pretty much @mhvelplund , I've no where to test it.
Anyways thanks for the support

**Pull request closed without merging**
