### PR TITLE
Moved variable comments to description tags

### PR DESCRIPTION
**Pull request by mhvelplund**
Description tags are visible in the [module repository](https://registry.terraform.io/modules/blinkist/airship-ecs-service/aws/0.8.8?tab=inputs) and make it easier to configure the plugin.

### CODE REVIEW

**Comment by maartenvanderhoef** [comment]
Hi @mhvelplund, thanks for helping out. We just made a big change to the variable structure, removing the maps as input as they we causing issues. Currently `variables.tf` has changed quite a lot, would you still care to take another look ?

**Comment by mhvelplund** [comment]
Hmm. I updated the PR, but now Travis chokes. I tried running the fmt step locally, and I didn't get an error ...

```bash
mads.hvelplund@PC19177 MINGW64 ~/Documents/terraform-aws-airship-ecs-service (master)
$ terraform fmt -write=false -diff=true -check=true

mads.hvelplund@PC19177 MINGW64 ~/Documents/terraform-aws-airship-ecs-service (master)
$ echo $?
0
```

I'm not sure what the problem is.

**Comment by maartenvanderhoef** [comment]
That's weird, because I'm getting the same with your branch. What tf version are you running ? What are you getting with `docker run --rm -v $(pwd):/data --workdir=/data -t hashicorp/terraform:0.11.13 fmt -write=false -diff=true -check=true` ?

If you're using VIM, please check out https://github.com/fatih/vim-hclfmt !

**Comment by mhvelplund** [comment]
@maartenvanderhoef it builds now.

**Comment by maartenvanderhoef** [comment]
@mhvelplund  Thanks Mads, let me merge this, and I'll add the missing ones.

**Pull request merged**
